name: Docs

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  docs:
    name: Update docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pdoc
        run: |
          pip install pdoc
      - name: Run pdoc
        run: |
          pdoc -o ./docs --docformat google isolate
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh_pages
      - name: Update docs
        run: |
          ls
          rm -rf gh_pages/*
          cp -R docs/* gh_pages/*
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          cd gh_pages
          git add *
          git commit -m "CI: Update docs for $(git rev-parse HEAD)"
          git push
